server:
  port: 2233
spring:
  redis:
    host: 127.0.0.1
    database: 3
    password: 123456
    port: 6379
    ssl: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-sample-user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application:
    name: springcloud-sample-oauth2

mybatis:
  type-aliases-package: com.yqh.springcloud.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.yqh.springcloud.common.config.BaseMapper
  not-empty: true
  identity: mysql
  style: camelhump
logging:
  level:
    org.springframework.security: DEBUG
eureka:
  instance:
    appname: springcloud-sample-oauth2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:9999/eureka/