server:
  port: 48080

spring:
  application:
    name: ribbon-server

eureka:
  instance:
    appname: ribbon-server
    prefer-ip-address: true
    metadata-map:
      user.name: admin
      user.password: admin
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:18761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

order-server:
  ribbon:
    ConnectTimeout: 10000 #单位ms,请求连接超时时间
    ReadTimeout: 10000 #单位ms,请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
