virtual:
  machine:
    ip: 10.134.240.116 #虚拟机地址

server:
  port: 18761
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    appname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:18761/eureka/
    register-with-eureka: false
    fetch-registry: false
#日志配置
logging:
  level:
    org.springframework.web: TRACE
    org.springframework.boot: INFO
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  file.max-history: 7