spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #签收模式 手动签收
        max-concurrency: 10 #最大并发
        concurrency: 5 #基本并发
        prefetch: 1 #限流策略，同一时间只有1条消息发送过来消费
    publisher-confirms: true
    publisher-returns: true
  application:
    name: rabbitmq-dome

server:
  port: 12345
  servlet:
    context-path: /

snowflake:
  data:
    center:
      id: 1
  worker:
    id: 2
